# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
author: Kaleb Olson
title: xzzy.xyz
email: kalebo@xzzy.xyz
description: Discount magic words
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xzzy.xyz" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  kalebo

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-sitemap
